### ISSUE TITLE
Unable to get to run

### ISSUE THREAD

**Issue by maxxadams** [digexp/dxsync#2]
Hello,
I was able to install and run the tool back at the beginning of the month.  Today I am getting 'node' is not recognized as an internal or external command, operable program or batch file.  When I try to verify node install I get the same error.  I am not sure where I should run 'node -v' and 'npm -v" but that is not working as well.  I can through my start menu bring up node and a prompt comes up.  I must be doing something wrong, but i cannot figure it as I am doing what I did the last time.  I have not upgrade any version I am at master.

Thank You,
Max

**Comment by mburati** [comment]
This tool pre-reqs, but does not bundle or ship node and npm, you would have installed those separately from the appropriate site.  If they were working previously on this system but are no longer found, then it is likely something changed (overwrote) your command path to no longer include the location where you had installed node / npm.  Are you logging in as the same user account you had installed node as?  It's possible that the command path was set up for an alternate user.

It's not clear from the question which OS you're running on, or which Node you installed (eg, the IBM SDK for Node product vs Node from nodejs.org)

For example, on my Windows system, using IBM SDK for Node,   I chose the alternate install location of c:\ibm\node , so that is in my PATH environment variable.     Also, since npm global installs place artifacts in a user specific application data location,   I have c:\users\mburati\AppData\Roaming\npm  in my Windows path on this system.   I have heard of some having an issue with that latter path not being set correctly by some node installs (not sure if that particular problem has affected both Linux and Windows users or only Windows users).

I hope that info helps,
..Mike Burati 
https://developer.ibm.com/digexp/
The postings on this site are my own and do not necessarily represent the positions, strategies, or opinions of IBM.

**Comment by maxxadams** [comment]
I followed the path to the node download.  I downloaded the .12 version as directed and installed.  Node lives in C:\Program Files\nodejs.  NPM lives in the same path and is in the node_modules folder.  Odd it worked before and not now.

**Comment by mburati** [comment]
Try "set PATH"  or "echo %PATH%" on the command line to see if that path is indeed in your Windows PATH environment variable.    If not, then maybe some other install since it had worked, overwrote your PATH env var.

If it's there but still not working, then it's not clear what's causing it, unless something corrupted the install somehow (again, that's a separate product, not part of this dxsync project, but rather the underlying framework/product that dxsync relies on and is built on).

You could try uninstalling and reinstalling node, if you have nothing that you need to save in your npm global repository,  or you could try just fixing the WIndows PATH var to include where you installed it to, if it's there and not-currupt and just missing from the PATH variable.

If you have nothing of value in your current npm install, then another option is to switch to using IBM SDK for Node.   See more about that here:  http://www.ibm.com/developerworks/web/nodesdk/

Note, if you're installing from nodejs.org,  before to get the latest 0.12.x version, which dxsync relies on and not the very latest verstion at nodejs.org.   Dxsync has external dependencies on other npm packages (see package.json)  and dxsync and those external dependencies have not been tested to work together on versions of node other than 0.12.x (where IBM's SDK for Node 1.2 is based on the 0.12.x stream).

I hope that info helps,
..Mike Burati 
https://developer.ibm.com/digexp/
The postings on this site are my own and do not necessarily represent the positions, strategies, or opinions of IBM.

**Comment by maxxadams** [comment]
the paths are there, but no dice.  I will uninstall node.  I will install the ibm SDK for node.  Where is the default install path for dxsync?   Do I need to uninstall dxsync that and reinstall?

**Comment by maxxadams** [comment]
Thank you for your help

**Comment by mburati** [comment]
If you go up to the root of this project and look at the install script (eg, install.cmd ) you'll see that it's using npm -g  which tells the node package manager (npm) to install it globally for that installation of npm (as opposed to just within the folder/project you run it in).   If you uninstall and reinstall node/npm, that repository may be cleared out so I suggest running the dxsync install again if you must reinstall node vs just fixing the PATH var.

I hope that info helps,
..Mike Burati 
https://developer.ibm.com/digexp/
The postings on this site are my own and do not necessarily represent the positions, strategies, or opinions of IBM.

**Comment by mburati** [comment]
@maxxadams, did you get this to work?  If so, we'd like to close this issue out.  Thanks.
